name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    concurrency: build
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
      - uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/pikdum/thistle_tea:latest
          platforms: linux/amd64
      - uses: snok/container-retention-policy@v2
        with:
          image-names: pikdum/thistle_tea
          cut-off: 1 day ago utc
          keep-at-least: 1
          account-type: personal
          token: ${{ secrets.GITHUB_TOKEN }}
          token-type: github-token
